name: wise_ultra_settings
description: A settings package to be used with wisemen backends in the context of ULTRA
version: 1.0.0

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # Wisemen
  wisecore:
    git:
      url: https://github.com/wisemen-digital/wisemen-flutter-packages.git
      ref: feature/wisemen-ultra-authentication
      path: packages/wisecore
  wise_theming: '>=1.0.0 <2.0.0'
  wisewidgetslibrary: '>=2.0.4 <3.0.0'
  wise_nav_bar: '>=0.0.0 <1.0.0'

  # Riverpod
  riverpod_annotation: '>=3.0.0 <4.0.0'
  riverpod: ">=3.0.0 <4.0.0"
  hooks_riverpod: '>=3.0.0 <4.0.0'
  flutter_riverpod: '>=3.0.0 <4.0.0'

  # Client
  wiseclient: '>=1.1.1 <2.0.0'

  # SVG
  flutter_svg: '>=2.1.0 <3.0.0'

  # Flutter sticky header
  flutter_sticky_header: '>=0.0.0 <1.0.0'

  # Package info
  package_info_plus: '>=9.0.0 <10.0.0'

  # Storage
  shared_preferences: ">=2.0.0 <3.0.0"

  # Auto Size Text
  auto_size_text: ">=3.0.0 <4.0.0"

  # Cached Network Image
  cached_network_image: ">=3.0.0 <4.0.0"

  # Flutter hooks
  flutter_hooks: ">=0.0.0 <1.0.0"

  # Drift
  drift: ">=2.0.0 <3.0.0"

  # Flutter platform alert
  flutter_platform_alert: 0.5.3

dev_dependencies:
  build_runner: ^2.4.15
  riverpod_generator: ^3.0.2
  drift_dev: ^2.26.0
  json_serializable: ^6.9.4
  # Static analysis & linting
  lints: ^5.1.1
  mocktail: ^1.0.4

  # Testing
  test: ^1.25.15

  # Mocking
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter