analyzer:
  errors:
    invalid_annotation_target: ignore
  plugins: 
    - custom_lint
  exclude: [build/**, lib/**.g.dart, lib/generated/**]

custom_lint:
  rules:
    - avoid_manual_providers_as_generated_provider_dependency: false
formatter:
      page_width: 150
linter:
  rules:
    avoid_print: true
    use_key_in_widget_constructors: false
    depend_on_referenced_packages: false
    prefer_single_quotes: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    deprecated_member_use_from_same_package: true
    invalid_case_patterns: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_self_assignments: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    always_declare_return_types: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    avoid_returning_this: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    constant_identifier_names: false
    directives_ordering: true
    empty_constructor_bodies: true
    eol_at_end_of_file: true
    exhaustive_cases: true
    flutter_style_todos: true
    matching_super_parameters: true
    no_literal_bool_comparisons: true
    no_runtimeType_toString: true
    non_constant_identifier_names: false
    noop_primitive_operations: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_contains: true
    require_trailing_commas: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    unnecessary_breaks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    use_enums: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true