import 'dart:io';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class AppTheme {
  static ThemeData baseTheme = ThemeData(
    useMaterial3: true,
    fontFamily: Platform.isIOS ? 'CupertinoSystemDisplay' : 'RobotoFlex',
    appBarTheme: const AppBarTheme(surfaceTintColor: Colors.transparent),
    splashFactory: Platform.isIOS
        ? NoSplash.splashFactory
        : null, //remove ripple effect on InkWell buttons on IOS
  );

  static ThemeData darkTheme = baseTheme.copyWith(
    applyElevationOverlayColor: true,
    brightness: Brightness.dark,
    buttonTheme: ButtonThemeData(
      colorScheme: const ColorScheme.dark(
        errorContainer: Color(0xffcf6679),
        inversePrimary: Color(0xff000000),
        inverseSurface: Color(0xffffffff),
        onErrorContainer: Color(0xff000000),
        onInverseSurface: Color(0xff121313),
        onPrimaryContainer: Color(0xff000000),
        onSecondaryContainer: Color(0xff000000),
        onSurfaceVariant: Color(0xffffffff),
        onTertiary: Color(0xff000000),
        onTertiaryContainer: Color(0xff000000),
        outline: Color(0xffffffff),
        outlineVariant: Color(0xffffffff),
        primary: Color(0xff64cfc2),
        primaryContainer: Color(0xff55b2a6),
        scrim: Color(0xff000000),
        secondary: Color(0xffe4a9ef),
        secondaryContainer: Color(0xffda81e8),
        shadow: Color(0xff000000),
        surface: Color(0xff121313),
        surfaceContainerHighest: Color(0xff121313),
        surfaceTint: Color(0xff64cfc2),
        tertiary: Color(0xffe4a9ef),
        tertiaryContainer: Color(0xffe4a9ef),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(2),
      ),
    ),
    canvasColor: const Color(0xff121313),
    cardColor: const Color(0xff121313),
    colorScheme: const ColorScheme.dark(
      errorContainer: Color(0xffcf6679),
      inversePrimary: Color(0xff000000),
      inverseSurface: Color(0xffffffff),
      onErrorContainer: Color(0xff000000),
      onInverseSurface: Color(0xff121313),
      onPrimaryContainer: Color(0xff000000),
      onSecondaryContainer: Color(0xff000000),
      onSurfaceVariant: Color(0xffffffff),
      onTertiary: Color(0xff000000),
      onTertiaryContainer: Color(0xff000000),
      outline: Color(0xffffffff),
      outlineVariant: Color(0xffffffff),
      primary: Color(0xff64cfc2),
      primaryContainer: Color(0xff55b2a6),
      scrim: Color(0xff000000),
      secondary: Color(0xffe4a9ef),
      secondaryContainer: Color(0xffda81e8),
      shadow: Color(0xff000000),
      surface: Color(0xff121313),
      surfaceContainerHighest: Color(0xff121313),
      surfaceTint: Color(0xff64cfc2),
      tertiary: Color(0xffe4a9ef),
      tertiaryContainer: Color(0xffe4a9ef),
    ),
    disabledColor: const Color(0x62ffffff),
    dividerColor: const Color(0x1fffffff),
    focusColor: const Color(0x1fffffff),
    highlightColor: const Color(0x40cccccc),
    hintColor: const Color(0x99ffffff),
    hoverColor: const Color(0x0affffff),
    iconTheme: const IconThemeData(color: Color(0xffffffff)),
    inputDecorationTheme: const InputDecorationTheme(),
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    primaryColor: const Color(0xff121313),
    primaryColorDark: const Color(0xff000000),
    primaryColorLight: const Color(0xff9e9e9e),
    primaryIconTheme: const IconThemeData(color: Color(0xffffffff)),
    primaryTextTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 96,
        fontWeight: FontWeight.w300,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 48,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 40,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 34,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 11,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 10,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 20,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    scaffoldBackgroundColor: const Color(0xff121313),
    secondaryHeaderColor: const Color(0xff616161),
    shadowColor: const Color(0xff000000),
    splashColor: const Color(0x40cccccc),
    splashFactory: InkRipple.splashFactory,
    textTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 96,
        fontWeight: FontWeight.w300,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 48,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 40,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 34,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 11,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 10,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 20,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xffffffff),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    typography: Typography.material2021(
      black: Typography.blackCupertino,
      dense: Typography.dense2021,
      englishLike: Typography.englishLike2021,
      tall: Typography.tall2021,
      white: Typography.whiteCupertino,
    ),
    unselectedWidgetColor: const Color(0xb3ffffff),
    visualDensity: VisualDensity.compact,
    cupertinoOverrideTheme: const CupertinoThemeData(
      primaryColor: Color(0xff64cfc2),
      primaryContrastingColor: Color(0xff55b2a6),
      barBackgroundColor: Color(0xff121313),
      scaffoldBackgroundColor: Color(0xff121313),
      textTheme: CupertinoTextThemeData(
        primaryColor: Color(0xffffffff),
        textStyle: TextStyle(
          color: Color(0xffffffff),
          fontSize: 16,
          fontWeight: FontWeight.w400,
        ),
      ),
    ),
    dialogTheme: const DialogThemeData(backgroundColor: Color(0xff121313)),
  );

  //light theme
  static ThemeData lightTheme = baseTheme.copyWith(
    applyElevationOverlayColor: false,
    brightness: Brightness.light,
    buttonTheme: ButtonThemeData(
      colorScheme: const ColorScheme.light(
        errorContainer: Color(0xffb00020),
        inversePrimary: Color(0xffffffff),
        inverseSurface: Color(0xff000000),
        onErrorContainer: Color(0xffffffff),
        onInverseSurface: Color(0xffe2e5ed),
        onPrimaryContainer: Color(0xffffffff),
        onSecondaryContainer: Color(0xff000000),
        onSurfaceVariant: Color(0xff000000),
        onTertiary: Color(0xff000000),
        onTertiaryContainer: Color(0xff000000),
        outline: Color(0xff000000),
        outlineVariant: Color(0xff000000),
        primary: Color(0xff892057),
        primaryContainer: Color(0xff62143d),
        scrim: Color(0xff000000),
        secondary: Color(0xff21561b),
        secondaryContainer: Color(0xff153c11),
        shadow: Color(0xff000000),
        surface: Color(0xffe2e5ed),
        surfaceContainerHighest: Color(0xffe2e5ed),
        surfaceTint: Color(0xff892057),
        tertiary: Color(0xff21561b),
        tertiaryContainer: Color(0xff21561b),
      ),
      padding: const EdgeInsets.symmetric(horizontal: 16),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(2),
      ),
    ),
    canvasColor: const Color(0xffe2e5ed),
    cardColor: const Color(0xffe2e5ed),
    colorScheme: const ColorScheme.light(
      errorContainer: Color(0xffb00020),
      inversePrimary: Color(0xffffffff),
      inverseSurface: Color(0xff000000),
      onErrorContainer: Color(0xffffffff),
      onInverseSurface: Color(0xffe2e5ed),
      onPrimaryContainer: Color(0xffffffff),
      onSecondaryContainer: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      onTertiary: Color(0xff000000),
      onTertiaryContainer: Color(0xff000000),
      outline: Color(0xff000000),
      outlineVariant: Color(0xff000000),
      primary: Color(0xff892057),
      primaryContainer: Color(0xff62143d),
      scrim: Color(0xff000000),
      secondary: Color(0xff21561b),
      secondaryContainer: Color(0xff153c11),
      shadow: Color(0xff000000),
      surface: Color(0xffe2e5ed),
      surfaceContainerHighest: Color(0xffe2e5ed),
      surfaceTint: Color(0xff892057),
      tertiary: Color(0xff21561b),
      tertiaryContainer: Color(0xff21561b),
    ),
    disabledColor: const Color(0x61000000),
    dividerColor: const Color(0x1f000000),
    focusColor: const Color(0x1f000000),
    highlightColor: const Color(0x66bcbcbc),
    hintColor: const Color(0x99000000),
    hoverColor: const Color(0x0a000000),
    iconTheme: const IconThemeData(color: Color(0xdd000000)),
    inputDecorationTheme: const InputDecorationTheme(),
    materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
    primaryColor: const Color(0xff892057),
    primaryColorDark: const Color(0xff1976d2),
    primaryColorLight: const Color(0xffbbdefb),
    primaryIconTheme: const IconThemeData(color: Color(0xffffffff)),
    primaryTextTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 96,
        fontWeight: FontWeight.w300,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 48,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 40,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 34,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 11,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 10,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 20,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xffe2e5ed),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    scaffoldBackgroundColor: const Color(0xffe2e5ed),
    secondaryHeaderColor: const Color(0xffe3f2fd),
    shadowColor: const Color(0xff000000),
    splashColor: const Color(0x66c8c8c8),
    splashFactory: InkRipple.splashFactory,
    textTheme: const TextTheme(
      bodyLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodyMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      bodySmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 12,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.4,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 96,
        fontWeight: FontWeight.w300,
        letterSpacing: -1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displayMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 60,
        fontWeight: FontWeight.w300,
        letterSpacing: -0.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      displaySmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 48,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 40,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 34,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      headlineSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 24,
        fontWeight: FontWeight.w400,
        letterSpacing: 0,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 1.25,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 11,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      labelSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 10,
        fontWeight: FontWeight.w400,
        letterSpacing: 1.5,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleLarge: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 20,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleMedium: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 16,
        fontWeight: FontWeight.w400,
        letterSpacing: 0.15,
        textBaseline: TextBaseline.alphabetic,
      ),
      titleSmall: TextStyle(
        color: Color(0xff000000),
        decoration: TextDecoration.none,
        fontSize: 14,
        fontWeight: FontWeight.w500,
        letterSpacing: 0.1,
        textBaseline: TextBaseline.alphabetic,
      ),
    ),
    typography: Typography.material2021(
      black: Typography.blackCupertino,
      dense: Typography.dense2021,
      englishLike: Typography.englishLike2021,
      tall: Typography.tall2021,
      white: Typography.whiteCupertino,
    ),
    unselectedWidgetColor: const Color(0x8a000000),
    visualDensity: VisualDensity.compact,
    cupertinoOverrideTheme: const CupertinoThemeData(
      primaryColor: Color(0xff892057),
      primaryContrastingColor: Color(0xff62143d),
      barBackgroundColor: Color(0xffe2e5ed),
      scaffoldBackgroundColor: Color(0xffe2e5ed),
      textTheme: CupertinoTextThemeData(
        primaryColor: Color(0xff000000),
        textStyle: TextStyle(
          color: Color(0xff000000),
          fontSize: 16,
          fontWeight: FontWeight.w400,
        ),
      ),
    ),
    dialogTheme: const DialogThemeData(backgroundColor: Color(0xffe2e5ed)),
  );
}
