name: wiseclient
description: A http client based on Dio with extra features and a few interceptors for basic functionality.
version: 1.1.2
homepage: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wiseclient
repository: https://github.com/wisemen-digital/flutter-networking-client/packages/wiseclient

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.19.5'
resolution: workspace
dependencies:
  # Flutter
  flutter:
    sdk: flutter

  # Dio
  dio: ^5.8.0+1
  fresh_dio: ^0.4.3

  # Secure storage
  flutter_secure_storage: ^10.0.0-beta.4
  
  # Logging & Debugging
  native_dio_adapter: ^1.4.0
  talker_dio_logger: ">=4.6.0 <5.0.0"

dev_dependencies:
  # Static analysis & linting
  lints: ^5.1.1
  mocktail: ^1.0.4

  # Testing
  test: ^1.25.15

  # Mocking
  mockito: ^5.4.0
  flutter_test:
    sdk: flutter
