// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

late final _class_SwiftTextClassifier = objc.getClass(
  "wise_text.SwiftTextClassifier",
);
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
late final _sel_classifyTextWithText_ = objc.registerName(
  "classifyTextWithText:",
);
final _objc_msgSend_1sotr3r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
typedef instancetype = ffi.Pointer<objc.ObjCObjectImpl>;
typedef Dartinstancetype = objc.ObjCObject;
late final _sel_init = objc.registerName("init");
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
late final _sel_new = objc.registerName("new");
late final _sel_allocWithZone_ = objc.registerName("allocWithZone:");
final _objc_msgSend_1cwp428 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.NSZone>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.NSZone>,
      )
    >();
late final _sel_alloc = objc.registerName("alloc");

/// SwiftTextClassifier
extension type SwiftTextClassifier._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [SwiftTextClassifier] that points to the same underlying object as [other].
  SwiftTextClassifier.as(objc.ObjCObject other) : object$ = other {
    assert(isA(object$));
  }

  /// Constructs a [SwiftTextClassifier] that wraps the given raw object pointer.
  SwiftTextClassifier.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [SwiftTextClassifier].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_SwiftTextClassifier,
  );

  /// alloc
  static SwiftTextClassifier alloc() {
    final $ret = _objc_msgSend_151sglz(_class_SwiftTextClassifier, _sel_alloc);
    return SwiftTextClassifier.fromPointer($ret, retain: false, release: true);
  }

  /// allocWithZone:
  static SwiftTextClassifier allocWithZone(ffi.Pointer<objc.NSZone> zone) {
    final $ret = _objc_msgSend_1cwp428(
      _class_SwiftTextClassifier,
      _sel_allocWithZone_,
      zone,
    );
    return SwiftTextClassifier.fromPointer($ret, retain: false, release: true);
  }

  /// new
  static SwiftTextClassifier new$() {
    final $ret = _objc_msgSend_151sglz(_class_SwiftTextClassifier, _sel_new);
    return SwiftTextClassifier.fromPointer($ret, retain: false, release: true);
  }

  /// Returns a new instance of SwiftTextClassifier constructed with the default `new` method.
  SwiftTextClassifier() : this.as(new$().object$);
}

extension SwiftTextClassifier$Methods on SwiftTextClassifier {
  /// Classifies <code>text</code> and returns a JSON array of spans as a String.
  /// A JSON string is used as the bridge type because it maps cleanly to a
  /// Dart <code>String</code> over the FFI/Objective-C interop layer; the Dart side
  /// decodes it into typed models.
  objc.NSString classifyTextWithText(objc.NSString text) {
    final $ret = _objc_msgSend_1sotr3r(
      object$.ref.pointer,
      _sel_classifyTextWithText_,
      text.ref.pointer,
    );
    return objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// init
  SwiftTextClassifier init() {
    objc.checkOsVersionInternal(
      'SwiftTextClassifier.init',
      iOS: (false, (2, 0, 0)),
      macOS: (false, (10, 0, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      object$.ref.retainAndReturnPointer(),
      _sel_init,
    );
    return SwiftTextClassifier.fromPointer($ret, retain: false, release: true);
  }
}
