// AUTO GENERATED BY JNIGEN 0.17.0. DO NOT EDIT!

// ignore_for_file: public_member_api_docs, sort_constructors_first, unnecessary_raw_strings, annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.example.wise_text.WiseTextPlugin`
extension type WiseTextPlugin._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/example/wise_text/WiseTextPlugin',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<WiseTextPlugin> type = $WiseTextPlugin$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Landroid/content/Context;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory WiseTextPlugin(
    Context context,
  ) {
    final _$$classRef = _class.reference;
    final _$context = context.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$context.pointer,
    ).object<WiseTextPlugin>();
  }
}

extension WiseTextPlugin$$Methods on WiseTextPlugin {
  static final _id_classifyText = WiseTextPlugin._class.instanceMethodId(
    r'classifyText',
    r'(Ljava/lang/String;Lkotlin/coroutines/Continuation;)Ljava/lang/Object;',
  );

  static final _classifyText =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Pointer<jni$_.Void>)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public suspend fun classifyText(text: kotlin.String): kotlin.IntArray`
  /// The returned object must be released after use, by calling the [release] method.
  core$_.Future<jni$_.JIntArray> classifyText(
    jni$_.JString string,
  ) async {
    final $p = jni$_.ReceivePort();
    final _$continuation = jni$_.ProtectedJniExtensions.newPortContinuation($p);
    final _$$selfRef = reference;
    final _$string = string.reference;
    final $r = _classifyText(
      _$$selfRef.pointer,
      _id_classifyText.pointer,
      _$string.pointer,
      _$continuation.pointer,
    ).object<jni$_.JObject>();
    _$continuation.release();
    jni$_.JObject $o;
    if ($r.isInstanceOf(jni$_.coroutineSingletonsClass)) {
      $r.release();
      final $a = await $p.first;
      $o = jni$_.JObject.fromReference(
        jni$_.JGlobalReference(jni$_.JObjectPtr.fromAddress($a)),
      );
      if ($o.isInstanceOf(jni$_.result$Class)) {
        $o = jni$_.resultValueField.get($o, const jni$_.$JObject$Type$());
      } else if ($o.isInstanceOf(jni$_.result$FailureClass)) {
        final $e = jni$_.failureExceptionField.get(
          $o,
          const jni$_.$JObject$Type$(),
        );
        $o.release();
        jni$_.Jni.throwException($e.reference.toPointer());
      }
    } else {
      $o = $r;
    }
    return $o.as<jni$_.JIntArray>(
      jni$_.JIntArray.type,
      releaseOriginal: true,
    );
  }
}

final class $WiseTextPlugin$Type$ extends jni$_.JType<WiseTextPlugin> {
  @jni$_.internal
  const $WiseTextPlugin$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/example/wise_text/WiseTextPlugin;';
}

/// from: `android.content.Context`
///
/// WARNING: Context is a stub. To generate bindings for this class, include
/// android.content.Context in your config's classes list.
///
extension type Context._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Context> type = $Context$Type$();
}

final class $Context$Type$ extends jni$_.JType<Context> {
  @jni$_.internal
  const $Context$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroid/content/Context;';
}

/// from: `kotlin.coroutines.Continuation`
///
/// WARNING: Continuation is a stub. To generate bindings for this class, include
/// kotlin.coroutines.Continuation in your config's classes list.
///
extension type Continuation._(jni$_.JObject _$this) implements jni$_.JObject {
  static const jni$_.JType<Continuation> type = $Continuation$Type$();
}

final class $Continuation$Type$ extends jni$_.JType<Continuation> {
  @jni$_.internal
  const $Continuation$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lkotlin/coroutines/Continuation;';
}
