name: wisecore
description: A flutter core project used by Wisemen. Comes with a bunch of generally useful extensions and functions.
version: 2.2.3
homepage: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wisecore
repository: https://github.com/wisemen-digital/wisemen-flutter-packages/packages/wisecore

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace
dependencies:
  # Flutter
  flutter:
    sdk: flutter
  intl: any

  # Riverpod
  riverpod: ">=3.0.0 <4.0.0"

  # Networking
  dio: ">=5.0.0 <6.0.0"

  # Storage
  shared_preferences: ">=2.0.0 <3.0.0"

  # Misc
  url_launcher: ">=6.0.0 <7.0.0"
  flutter_platform_alert: ^0.5.3

  # platform interfaces
  plugin_platform_interface: any
  url_launcher_platform_interface: any

dev_dependencies:
  # Static analysis & linting
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  dependency_validator: ^5.0.2

  # Testing
  test: ^1.25.15

  # Mocking
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter