
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run linter and analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true 
      
      - run: flutter --version
      
      - name: Run flutter pub get
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format . --set-exit-if-changed

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Run Flutter WiseClient tests
        run: flutter test --no-pub --coverage --coverage-path=./coverage/lcov.wiseclient.info
        working-directory: packages/wiseclient
      
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 80
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: code-coverage-report
          working-directory: packages/wiseclient
          update-comment: true