
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run linter and analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            wiseclient:
              - ./.github/workflows/dart.yml
              - ./.github/actions/package/action.yaml
              - packages/wiseclient/**
            wisecore:
              - ./.github/workflows/dart.yml
              - ./.github/actions/package/action.yaml
              - packages/wisecore/**
            wisewidgetslibrary:
              - ./.github/workflows/dart.yml
              - ./.github/actions/package/action.yaml
              - packages/wisewidgetslibrary/**
            wise_nav_bar:
              - ./.github/workflows/dart.yml
              - ./.github/actions/package/action.yaml
              - packages/wise_nav_bar/**
      
      - if: steps.changes.outputs.wiseclient == 'true'
        uses: ./.github/actions/package
        with:
          working_directory: packages/wiseclient
          min_coverage: 20
      
      - if: steps.changes.outputs.wisecore == 'true'
        uses: ./.github/actions/package
        with:
          working_directory: packages/wisecore
          min_coverage: 80
      
      - if: steps.changes.outputs.wisewidgetslibrary == 'true'
        uses: ./.github/actions/package
        with:
          working_directory: packages/wisewidgetslibrary
          min_coverage: 0

      - if: steps.changes.outputs.wise_nav_bar == 'true'
        uses: ./.github/actions/package
        with:
          working_directory: packages/wise_nav_bar
          min_coverage: 0