
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run linter and analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:"
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      
      - run: flutter --version
      
      - name: Run flutter pub get
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format . --set-exit-if-changed

      - name: Analyze project source
        run: dart analyze --fatal-infos --fatal-warnings

      - name: Run Flutter WiseClient tests
        run: cd packages/wiseclient && flutter test --no-pub --coverage
      
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: packages/wiseclient/coverage/lcov.info
          minimum-coverage: 20
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: packages/wiseclient