# .github/workflows/publish.yml
name: Publish to pub.dev

on:
    workflow_dispatch: # Allows manual triggers with dropdown options
      inputs:
        package_name:
          description: "Select the package to publish"
          required: true
          type: choice
          options:
            - "wisecore"
            - "wiseclient"
            - "wisewidgetslibrary"
          default: "wisecore"
        tag_version:
          description: "Tag version ie. 1.0.0"
          required: true
          default: ""

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dart-lang/setup-dart@v1
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Install dependencies
        run: flutter pub get

      - name: Fix analysis issues
        run: dart fix --apply

      - name: Format
        run: dart format .
        
      - name: Publish
        run: |
          cd packages/${{ github.event.inputs.package_name }}
          dart pub publish --force

      - name: Create Git Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ github.event.inputs.package_name }} v${{ github.event.inputs.tag_version }}"
          message: "${{ github.event.inputs.package_name }} Release v${{ github.event.inputs.tag_version }}"
          force_push_tag: true
