name: Publish to pub.dev

on:
  push:
    tags:
      - "wisecore-v*"
      - "wiseclient-v*"
      - "wisewidgetslibrary-v*"
      - "wise_nav_bar-v*"
      - "wise_zitadel_login-v*"
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dart-lang/setup-dart@v1
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
      - name: Install dependencies
        run: flutter pub get

      - name: Fix analysis issues
        run: dart fix --apply

      - name: Format
        run: dart format .
        
      - name: Extract package name from tag
        id: extract
        run: |
          TAG_NAME=${{ github.ref_name }}  # Extracts the tag name
          PACKAGE_NAME=$(echo "$TAG_NAME" | sed -E 's/-v[0-9]+\.[0-9]+\.[0-9]+//')  # Extracts package name
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Publish to pub.dev
        run: |
          cd packages/${{ env.PACKAGE_NAME }}
          dart pub publish --force
